inherit_from:
  - "https://www.goodcop.style/tabs.yml"

AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false

Layout/HashAlignment:
  Enabled: false

Layout/MultilineArrayLineBreaks:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/EndAlignment:
  EnforcedStyleAlignWith: keyword

Layout/MultilineAssignmentLayout:
  Enabled: false

Style/EmptyElse:
  AllowComments: true

Layout/SpaceAroundOperators:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/EmptyLineAfterMultilineCondition:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false
