name: Ruby

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@f0adcbc13299b38a289a1c914af4ad137ca6bb54
    with:
      engine: all
      min_version: 3.1

  test:
    needs: ruby-versions
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ${{ fromJson(needs.ruby-versions.outputs.versions) }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install dependencies
        run: bundle install --without development
      - name: Quickdraw tests
        run: bundle exec qt -t 1 "./test/**/*.test.rb"
